spring:

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: SA
    password:

  liquibase:
    change-log: classpath:db/changelog/master.xml

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate


account-app:

  money:
    scale: 10
    rounding-mode: half_up

  currency-converter:
    mock:
      supported-currencies: USD, EUR, AUD
      exchange-rates:
        USDEUR: 1.1003280871
        USDAUD: 1.50
        EURUSD: 0.907
        EURAUD: 1.38907
        AUDUSD: 0.65000342
        AUDEUR: 0.58202
